### PR TITLE
Added dark mode feature, simple design system with css and design enhancement.

### PR DESCRIPTION
**Pull request by Mustafa-Suleiman**
What has changed: 

1. Deleted the static webpack build folder, no need for it.
2. Added the dark mode feature, which required a restructure of the CSS code, Here is what changed:
- theme state is managed by local storage [light mode is the default].
- created a simple system design with CSS variables.
- converted all hard-coded CSS styles to CSS variables, allowing us to change the style globally with a single line of code.
- simple animation transition between dark and light mode.

3. Design enhancement, better ui/ux, and color palettes for the light and dark themes

- changed the brand colors for a modern one.
- hero section text and nav bar links are vertically centered.
- changed the hero image to a clean looking portrait.
- some margins and paddings here and there :D
- moved the copyright element to the footer component.
- The color of the logo changes depending on the theme.
- The border style was changed from solid to dashed.

<p align='center' ><b>--Before--<b></p>

homepage

<p align='center' ><b>--After--<b></p>

screencapture-localhost-3000-2023-01-29-01_39_39

### CODE REVIEW

**Comment by Mustafa-Suleiman** [comment]
@sarkartanmay393 hey, when will you merge this pull?

**Comment by sarkartanmay393** [comment]
@Mustafa-Suleiman Can you update all of your code? I've added lot of new components, and now it needs to be synced together.

**Comment by Mustafa-Suleiman** [comment]
> @Mustafa-Suleiman Can you update all of your code? I've added lot of new components, and now it needs to be synced together.

okay, I will do it, but can you hold any commits on the main until we merge this pull?

**Comment by sarkartanmay393** [comment]
@Mustafa-Suleiman Sorry for my actions man. I didn't notice your message earlier. Extremely sorry for that, and yeah I can definitely hold commits. You just ping me anytime.

**Comment by Mustafa-Suleiman** [comment]
> @Mustafa-Suleiman Sorry for my actions man. I didn't notice your message earlier. Extremely sorry for that, and yeah I can definitely hold commits. You just ping me anytime.

np at all, I will be available tomorrow, so please mention me when you are ready.

**Comment by sarkartanmay393** [comment]
> y for my actions man. I didn't notice your message earlier. Extremely sorry for that, and yeah I can definitely hold commits. You just ping me anytime.

I am not pushing any new changes, so you can just sync your changes as soon as possible.

**Comment by Mustafa-Suleiman** [comment]
> > y for my actions man. I didn't notice your message earlier. Extremely sorry for that, and yeah I can definitely hold commits. You just ping me anytime.
> 
> I am not pushing any new changes, so you can just sync your changes as soon as possible.

you can merge now 👯

**Review by sarkartanmay393 — COMMENTED** [review]
This dark mode is changing my whole website's look. It doesn't look same style as mine to me. There is so lot to change. If you wanna make it complete, make it more minimal and default mode is dark, you just need to implement light mode.

**Pull request closed without merging**
